/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * TixTrack
 * Track your tickets
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSubjectDto,
  SubjectResponseDto,
  UpdateSubjectDto
} from '../tixTrack.schemas';

import { customInstance } from '../../client';




export const subjectControllerFindAll = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<SubjectResponseDto[]>(
      {url: `/subject`, method: 'GET', signal
    },
      );
    }
  



export const getSubjectControllerFindAllQueryKey = () => {
    return [
    `/subject`
    ] as const;
    }

    
export const getSubjectControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof subjectControllerFindAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubjectControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof subjectControllerFindAll>>> = ({ signal }) => subjectControllerFindAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubjectControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof subjectControllerFindAll>>>
export type SubjectControllerFindAllQueryError = unknown


export function useSubjectControllerFindAll<TData = Awaited<ReturnType<typeof subjectControllerFindAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subjectControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof subjectControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubjectControllerFindAll<TData = Awaited<ReturnType<typeof subjectControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subjectControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof subjectControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubjectControllerFindAll<TData = Awaited<ReturnType<typeof subjectControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSubjectControllerFindAll<TData = Awaited<ReturnType<typeof subjectControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubjectControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const subjectControllerCreate = (
    createSubjectDto: CreateSubjectDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SubjectResponseDto>(
      {url: `/subject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSubjectDto, signal
    },
      );
    }
  


export const getSubjectControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subjectControllerCreate>>, TError,{data: CreateSubjectDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof subjectControllerCreate>>, TError,{data: CreateSubjectDto}, TContext> => {

const mutationKey = ['subjectControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subjectControllerCreate>>, {data: CreateSubjectDto}> = (props) => {
          const {data} = props ?? {};

          return  subjectControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubjectControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof subjectControllerCreate>>>
    export type SubjectControllerCreateMutationBody = CreateSubjectDto
    export type SubjectControllerCreateMutationError = unknown

    export const useSubjectControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subjectControllerCreate>>, TError,{data: CreateSubjectDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subjectControllerCreate>>,
        TError,
        {data: CreateSubjectDto},
        TContext
      > => {

      const mutationOptions = getSubjectControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const subjectControllerFindOneById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SubjectResponseDto>(
      {url: `/subject/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getSubjectControllerFindOneByIdQueryKey = (id?: string,) => {
    return [
    `/subject/${id}`
    ] as const;
    }

    
export const getSubjectControllerFindOneByIdQueryOptions = <TData = Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubjectControllerFindOneByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof subjectControllerFindOneById>>> = ({ signal }) => subjectControllerFindOneById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubjectControllerFindOneByIdQueryResult = NonNullable<Awaited<ReturnType<typeof subjectControllerFindOneById>>>
export type SubjectControllerFindOneByIdQueryError = void


export function useSubjectControllerFindOneById<TData = Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subjectControllerFindOneById>>,
          TError,
          Awaited<ReturnType<typeof subjectControllerFindOneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubjectControllerFindOneById<TData = Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subjectControllerFindOneById>>,
          TError,
          Awaited<ReturnType<typeof subjectControllerFindOneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubjectControllerFindOneById<TData = Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSubjectControllerFindOneById<TData = Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subjectControllerFindOneById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubjectControllerFindOneByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const subjectControllerUpdate = (
    id: string,
    updateSubjectDto: UpdateSubjectDto,
 ) => {
      
      
      return customInstance<SubjectResponseDto>(
      {url: `/subject/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSubjectDto
    },
      );
    }
  


export const getSubjectControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subjectControllerUpdate>>, TError,{id: string;data: UpdateSubjectDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof subjectControllerUpdate>>, TError,{id: string;data: UpdateSubjectDto}, TContext> => {

const mutationKey = ['subjectControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subjectControllerUpdate>>, {id: string;data: UpdateSubjectDto}> = (props) => {
          const {id,data} = props ?? {};

          return  subjectControllerUpdate(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubjectControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof subjectControllerUpdate>>>
    export type SubjectControllerUpdateMutationBody = UpdateSubjectDto
    export type SubjectControllerUpdateMutationError = void

    export const useSubjectControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subjectControllerUpdate>>, TError,{id: string;data: UpdateSubjectDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subjectControllerUpdate>>,
        TError,
        {id: string;data: UpdateSubjectDto},
        TContext
      > => {

      const mutationOptions = getSubjectControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const subjectControllerDelete = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/subject/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getSubjectControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subjectControllerDelete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof subjectControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['subjectControllerDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subjectControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  subjectControllerDelete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubjectControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof subjectControllerDelete>>>
    
    export type SubjectControllerDeleteMutationError = void

    export const useSubjectControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subjectControllerDelete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subjectControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getSubjectControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    