/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * TixTrack
 * Track your tickets
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTicketDto,
  UpdateTicketDto
} from '../tixTrack.schemas';

import { customInstance } from '../../client';




export const ticketControllerFindAll = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/ticket`, method: 'GET', signal
    },
      );
    }
  



export const getTicketControllerFindAllQueryKey = () => {
    return [
    `/ticket`
    ] as const;
    }

    
export const getTicketControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof ticketControllerFindAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTicketControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ticketControllerFindAll>>> = ({ signal }) => ticketControllerFindAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TicketControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof ticketControllerFindAll>>>
export type TicketControllerFindAllQueryError = unknown


export function useTicketControllerFindAll<TData = Awaited<ReturnType<typeof ticketControllerFindAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ticketControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof ticketControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTicketControllerFindAll<TData = Awaited<ReturnType<typeof ticketControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ticketControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof ticketControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTicketControllerFindAll<TData = Awaited<ReturnType<typeof ticketControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTicketControllerFindAll<TData = Awaited<ReturnType<typeof ticketControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTicketControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const ticketControllerCreate = (
    createTicketDto: CreateTicketDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/ticket`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTicketDto, signal
    },
      );
    }
  


export const getTicketControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ticketControllerCreate>>, TError,{data: CreateTicketDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof ticketControllerCreate>>, TError,{data: CreateTicketDto}, TContext> => {

const mutationKey = ['ticketControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ticketControllerCreate>>, {data: CreateTicketDto}> = (props) => {
          const {data} = props ?? {};

          return  ticketControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TicketControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof ticketControllerCreate>>>
    export type TicketControllerCreateMutationBody = CreateTicketDto
    export type TicketControllerCreateMutationError = unknown

    export const useTicketControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ticketControllerCreate>>, TError,{data: CreateTicketDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ticketControllerCreate>>,
        TError,
        {data: CreateTicketDto},
        TContext
      > => {

      const mutationOptions = getTicketControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const ticketControllerFindOneById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/ticket/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getTicketControllerFindOneByIdQueryKey = (id?: string,) => {
    return [
    `/ticket/${id}`
    ] as const;
    }

    
export const getTicketControllerFindOneByIdQueryOptions = <TData = Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTicketControllerFindOneByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ticketControllerFindOneById>>> = ({ signal }) => ticketControllerFindOneById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TicketControllerFindOneByIdQueryResult = NonNullable<Awaited<ReturnType<typeof ticketControllerFindOneById>>>
export type TicketControllerFindOneByIdQueryError = unknown


export function useTicketControllerFindOneById<TData = Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ticketControllerFindOneById>>,
          TError,
          Awaited<ReturnType<typeof ticketControllerFindOneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTicketControllerFindOneById<TData = Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ticketControllerFindOneById>>,
          TError,
          Awaited<ReturnType<typeof ticketControllerFindOneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTicketControllerFindOneById<TData = Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTicketControllerFindOneById<TData = Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerFindOneById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTicketControllerFindOneByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const ticketControllerUpdate = (
    id: string,
    updateTicketDto: UpdateTicketDto,
 ) => {
      
      
      return customInstance<void>(
      {url: `/ticket/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTicketDto
    },
      );
    }
  


export const getTicketControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ticketControllerUpdate>>, TError,{id: string;data: UpdateTicketDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof ticketControllerUpdate>>, TError,{id: string;data: UpdateTicketDto}, TContext> => {

const mutationKey = ['ticketControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ticketControllerUpdate>>, {id: string;data: UpdateTicketDto}> = (props) => {
          const {id,data} = props ?? {};

          return  ticketControllerUpdate(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TicketControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof ticketControllerUpdate>>>
    export type TicketControllerUpdateMutationBody = UpdateTicketDto
    export type TicketControllerUpdateMutationError = unknown

    export const useTicketControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ticketControllerUpdate>>, TError,{id: string;data: UpdateTicketDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ticketControllerUpdate>>,
        TError,
        {id: string;data: UpdateTicketDto},
        TContext
      > => {

      const mutationOptions = getTicketControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const ticketControllerDelete = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/ticket/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getTicketControllerDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ticketControllerDelete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof ticketControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['ticketControllerDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ticketControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  ticketControllerDelete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TicketControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof ticketControllerDelete>>>
    
    export type TicketControllerDeleteMutationError = unknown

    export const useTicketControllerDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ticketControllerDelete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ticketControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getTicketControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    