/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * TixTrack
 * Track your tickets
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateServiceDto,
  ServiceResponseDto,
  UpdateServiceDto
} from '../tixTrack.schemas';

import { customInstance } from '../../client';




export const serviceControllerFindAll = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ServiceResponseDto[]>(
      {url: `/service`, method: 'GET', signal
    },
      );
    }
  



export const getServiceControllerFindAllQueryKey = () => {
    return [
    `/service`
    ] as const;
    }

    
export const getServiceControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof serviceControllerFindAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceControllerFindAll>>> = ({ signal }) => serviceControllerFindAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof serviceControllerFindAll>>>
export type ServiceControllerFindAllQueryError = unknown


export function useServiceControllerFindAll<TData = Awaited<ReturnType<typeof serviceControllerFindAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerFindAll<TData = Awaited<ReturnType<typeof serviceControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerFindAll<TData = Awaited<ReturnType<typeof serviceControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceControllerFindAll<TData = Awaited<ReturnType<typeof serviceControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const serviceControllerCreate = (
    createServiceDto: CreateServiceDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ServiceResponseDto>(
      {url: `/service`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createServiceDto, signal
    },
      );
    }
  


export const getServiceControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceControllerCreate>>, TError,{data: CreateServiceDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof serviceControllerCreate>>, TError,{data: CreateServiceDto}, TContext> => {

const mutationKey = ['serviceControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof serviceControllerCreate>>, {data: CreateServiceDto}> = (props) => {
          const {data} = props ?? {};

          return  serviceControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ServiceControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof serviceControllerCreate>>>
    export type ServiceControllerCreateMutationBody = CreateServiceDto
    export type ServiceControllerCreateMutationError = unknown

    export const useServiceControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceControllerCreate>>, TError,{data: CreateServiceDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof serviceControllerCreate>>,
        TError,
        {data: CreateServiceDto},
        TContext
      > => {

      const mutationOptions = getServiceControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const serviceControllerFindOneById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ServiceResponseDto>(
      {url: `/service/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getServiceControllerFindOneByIdQueryKey = (id?: string,) => {
    return [
    `/service/${id}`
    ] as const;
    }

    
export const getServiceControllerFindOneByIdQueryOptions = <TData = Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceControllerFindOneByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceControllerFindOneById>>> = ({ signal }) => serviceControllerFindOneById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceControllerFindOneByIdQueryResult = NonNullable<Awaited<ReturnType<typeof serviceControllerFindOneById>>>
export type ServiceControllerFindOneByIdQueryError = void


export function useServiceControllerFindOneById<TData = Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerFindOneById>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerFindOneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerFindOneById<TData = Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerFindOneById>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerFindOneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerFindOneById<TData = Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceControllerFindOneById<TData = Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerFindOneById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceControllerFindOneByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const serviceControllerUpdate = (
    id: string,
    updateServiceDto: UpdateServiceDto,
 ) => {
      
      
      return customInstance<ServiceResponseDto>(
      {url: `/service/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateServiceDto
    },
      );
    }
  


export const getServiceControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceControllerUpdate>>, TError,{id: string;data: UpdateServiceDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof serviceControllerUpdate>>, TError,{id: string;data: UpdateServiceDto}, TContext> => {

const mutationKey = ['serviceControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof serviceControllerUpdate>>, {id: string;data: UpdateServiceDto}> = (props) => {
          const {id,data} = props ?? {};

          return  serviceControllerUpdate(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ServiceControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof serviceControllerUpdate>>>
    export type ServiceControllerUpdateMutationBody = UpdateServiceDto
    export type ServiceControllerUpdateMutationError = void

    export const useServiceControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceControllerUpdate>>, TError,{id: string;data: UpdateServiceDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof serviceControllerUpdate>>,
        TError,
        {id: string;data: UpdateServiceDto},
        TContext
      > => {

      const mutationOptions = getServiceControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const serviceControllerDelete = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/service/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getServiceControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceControllerDelete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof serviceControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['serviceControllerDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof serviceControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  serviceControllerDelete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ServiceControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof serviceControllerDelete>>>
    
    export type ServiceControllerDeleteMutationError = void

    export const useServiceControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceControllerDelete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof serviceControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getServiceControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    