/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * TixTrack
 * Track your tickets
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../client';




export const commonControllerFindRolesByApp = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/common/roles`, method: 'GET', signal
    },
      );
    }
  



export const getCommonControllerFindRolesByAppQueryKey = () => {
    return [
    `/common/roles`
    ] as const;
    }

    
export const getCommonControllerFindRolesByAppQueryOptions = <TData = Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCommonControllerFindRolesByAppQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof commonControllerFindRolesByApp>>> = ({ signal }) => commonControllerFindRolesByApp(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CommonControllerFindRolesByAppQueryResult = NonNullable<Awaited<ReturnType<typeof commonControllerFindRolesByApp>>>
export type CommonControllerFindRolesByAppQueryError = unknown


export function useCommonControllerFindRolesByApp<TData = Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof commonControllerFindRolesByApp>>,
          TError,
          Awaited<ReturnType<typeof commonControllerFindRolesByApp>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCommonControllerFindRolesByApp<TData = Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof commonControllerFindRolesByApp>>,
          TError,
          Awaited<ReturnType<typeof commonControllerFindRolesByApp>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCommonControllerFindRolesByApp<TData = Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCommonControllerFindRolesByApp<TData = Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindRolesByApp>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCommonControllerFindRolesByAppQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const commonControllerFindUserRoles = (
    userId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/common/roles/${userId}`, method: 'GET', signal
    },
      );
    }
  



export const getCommonControllerFindUserRolesQueryKey = (userId?: string,) => {
    return [
    `/common/roles/${userId}`
    ] as const;
    }

    
export const getCommonControllerFindUserRolesQueryOptions = <TData = Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError = unknown>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCommonControllerFindUserRolesQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof commonControllerFindUserRoles>>> = ({ signal }) => commonControllerFindUserRoles(userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CommonControllerFindUserRolesQueryResult = NonNullable<Awaited<ReturnType<typeof commonControllerFindUserRoles>>>
export type CommonControllerFindUserRolesQueryError = unknown


export function useCommonControllerFindUserRoles<TData = Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError = unknown>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof commonControllerFindUserRoles>>,
          TError,
          Awaited<ReturnType<typeof commonControllerFindUserRoles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCommonControllerFindUserRoles<TData = Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof commonControllerFindUserRoles>>,
          TError,
          Awaited<ReturnType<typeof commonControllerFindUserRoles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCommonControllerFindUserRoles<TData = Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCommonControllerFindUserRoles<TData = Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof commonControllerFindUserRoles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCommonControllerFindUserRolesQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




