/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * TixTrack
 * Track your tickets
 * OpenAPI spec version: 1.0
 */
export interface SubjectResponseDto {
  /** Id of the subject */
  id: string;
  /**
   * Name of the subject
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Subject description
   * @minLength 1
   * @maxLength 255
   */
  description?: string;
  /** Service ID of the subject */
  serviceId: string;
}

export interface ServiceResponseDto {
  /** Id of the service */
  id: string;
  /**
   * Name of the service
   * @minLength 1
   * @maxLength 45
   */
  name: string;
  /**
   * Description of the service
   * @minLength 1
   * @maxLength 255
   */
  description?: string;
  /** Subjects of the service */
  subjects: SubjectResponseDto[];
}

export interface CreateServiceDto {
  /**
   * Name of the service
   * @minLength 1
   * @maxLength 45
   */
  name: string;
  /**
   * Description of the service
   * @minLength 1
   * @maxLength 255
   */
  description?: string;
}

export interface UpdateServiceDto {
  /**
   * Name of the service
   * @minLength 1
   * @maxLength 45
   */
  name?: string;
  /**
   * Description of the service
   * @minLength 1
   * @maxLength 255
   */
  description?: string;
}

export interface CreateSubjectDto {
  /**
   * Subject itself
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Subject description
   * @minLength 1
   * @maxLength 255
   */
  description?: string;
  /** Service ID associated with the subject */
  serviceId: string;
}

export interface UpdateSubjectDto {
  /**
   * Subject itself
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /**
   * Subject description
   * @minLength 1
   * @maxLength 255
   */
  description?: string;
  /** Service ID associated with the subject */
  serviceId?: string;
}

/**
 * Current status of the ticket
 */
export type TicketStatus = typeof TicketStatus[keyof typeof TicketStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TicketStatus = {
  open: 'open',
  in_progress: 'in progress',
  resolved: 'resolved',
  closed: 'closed',
} as const;

/**
 * Priority of the ticket
 */
export type TicketPriority = typeof TicketPriority[keyof typeof TicketPriority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TicketPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;

export interface CreateTicketDto {
  /**
   * Firstname of the ticket
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /**
   * Firstname of the ticket
   * @minLength 1
   * @maxLength 255
   */
  description: string;
  /** Current status of the ticket */
  status?: TicketStatus;
  /** Priority of the ticket */
  priority?: TicketPriority;
  /** Service ID associated with the subject */
  creatorId: string;
  /** Service ID associated with the subject */
  assigneeId: string;
  /** Service ID associated with the subject */
  subjectId: string;
  /** When the ticket was resolved */
  resolvedAt?: string;
}

export interface UpdateTicketDto {
  /**
   * Firstname of the ticket
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
  /**
   * Firstname of the ticket
   * @minLength 1
   * @maxLength 255
   */
  description?: string;
  /** Current status of the ticket */
  status?: TicketStatus;
  /** Priority of the ticket */
  priority?: TicketPriority;
  /** Service ID associated with the subject */
  creatorId?: string;
  /** Service ID associated with the subject */
  assigneeId?: string;
  /** Service ID associated with the subject */
  subjectId?: string;
  /** When the ticket was resolved */
  resolvedAt?: string;
}

/**
 * @nullable
 */
export type HealthControllerCheck200Info = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

/**
 * @nullable
 */
export type HealthControllerCheck200Error = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

export type HealthControllerCheck200Details = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }};

export type HealthControllerCheck200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck200Info;
  /** @nullable */
  error?: HealthControllerCheck200Error;
  details?: HealthControllerCheck200Details;
};

/**
 * @nullable
 */
export type HealthControllerCheck503Info = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

/**
 * @nullable
 */
export type HealthControllerCheck503Error = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

export type HealthControllerCheck503Details = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }};

export type HealthControllerCheck503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};

